from __future__ import annotations

import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NOTICE = ROOT / "frontend/src/components/aiops/AiFallbackNotice.tsx"
HELPER = ROOT / "frontend/src/helpers/aiFallback.ts"
ANALYSIS_PAGE = ROOT / "frontend/src/pages/ai-analysis/index.tsx"
REPORTS_PAGE = ROOT / "frontend/src/pages/reports/index.tsx"


def is_ollama_fallback(analysis: dict) -> bool:
    return analysis.get("fallbackUsed") is True or analysis.get("fallback_used") is True


def build_fallback_notice_copy(analysis: dict) -> dict | None:
    if not is_ollama_fallback(analysis):
        return None
    return {
        "title": "AI fallback used",
        "introduction": "The Ollama model could not be used for this analysis.",
        "reason": analysis.get("fallbackReason") or analysis.get("fallback_reason"),
        "engineNote": "The diagnostic below was generated by the deterministic rules engine.",
        "requestedProvider": analysis.get("requestedProvider")
        or analysis.get("requested_provider")
        or "ollama",
        "requestedModel": analysis.get("model"),
        "code": analysis.get("fallbackReasonCode") or analysis.get("fallback_reason_code"),
    }


class FrontendFallbackNoticeTests(unittest.TestCase):
    def test_notice_and_pages_render_fallback_reason(self) -> None:
        notice = NOTICE.read_text(encoding="utf-8")
        helper = HELPER.read_text(encoding="utf-8")
        analysis_page = ANALYSIS_PAGE.read_text(encoding="utf-8")
        reports_page = REPORTS_PAGE.read_text(encoding="utf-8")
        self.assertIn("AI fallback used", helper)
        self.assertIn("The diagnostic below was generated by the deterministic rules engine.", helper)
        self.assertIn("buildFallbackNoticeCopy", notice)
        self.assertIn("AiFallbackNotice", analysis_page)
        self.assertIn("AiFallbackNotice", reports_page)
        self.assertIn("Fallback code:", notice)

    def test_timeout_fallback_copy_is_operator_facing(self) -> None:
        notice = build_fallback_notice_copy(
            {
                "provider": "rules",
                "requestedProvider": "ollama",
                "model": "llama3.2:3b",
                "fallbackUsed": True,
                "fallbackReasonCode": "OLLAMA_TIMEOUT",
                "fallbackReason": "The local AI model did not respond within the configured timeout (300 seconds).",
            }
        )
        assert notice is not None
        self.assertEqual(notice["title"], "AI fallback used")
        self.assertIn("timeout", notice["reason"].lower())
        self.assertEqual(notice["code"], "OLLAMA_TIMEOUT")
        self.assertEqual(notice["requestedModel"], "llama3.2:3b")
        self.assertNotIn("Traceback", notice["reason"])

    def test_direct_rules_selection_does_not_render_ollama_failure(self) -> None:
        self.assertIsNone(
            build_fallback_notice_copy(
                {
                    "provider": "rules",
                    "requestedProvider": "rules",
                    "fallbackUsed": False,
                    "fallbackReasonCode": None,
                    "fallbackReason": None,
                }
            )
        )

    def test_analysis_pages_show_cache_status_not_as_a_warning(self) -> None:
        helper = HELPER.read_text(encoding="utf-8")
        analysis_page = ANALYSIS_PAGE.read_text(encoding="utf-8")
        reports_page = REPORTS_PAGE.read_text(encoding="utf-8")
        self.assertIn("formatAnalysisDuration", helper)
        self.assertIn("isCacheHit", helper)
        self.assertIn("Cached:", analysis_page)
        self.assertIn("Analysis time:", analysis_page)
        self.assertIn("Cached:", reports_page)
        self.assertNotIn("severity=\"error\"", analysis_page.split("Cached:")[1][:200])

    def test_duration_formatting_contract(self) -> None:
        helper = HELPER.read_text(encoding="utf-8")
        self.assertIn("export function formatAnalysisDuration", helper)
        self.assertIn("durationMs < 1000", helper)
        self.assertIn("${minutes}m ${seconds}s", helper)


if __name__ == "__main__":
    unittest.main()
