export type FallbackMetadata = {
  provider?: string;
  model?: string | null;
  requestedProvider?: string | null;
  requested_provider?: string | null;
  fallbackUsed?: boolean;
  fallback_used?: boolean;
  fallbackReasonCode?: string | null;
  fallback_reason_code?: string | null;
  fallbackReason?: string | null;
  fallback_reason?: string | null;
  cacheHit?: boolean;
  cache_hit?: boolean;
  analysisDurationMs?: number | null;
  analysis_duration_ms?: number | null;
  contextFingerprint?: string | null;
  context_fingerprint?: string | null;
};

export interface IncidentAnalysis extends FallbackMetadata {
  summary: string;
  priority: string;
  impact: string;
  risk: string;
  probable_causes: string[];
  suggested_actions: string[];
  diagnostic_commands: string[];
  provider: string;
}

export function normalizeIncidentAnalysis(raw: IncidentAnalysis): IncidentAnalysis {
  return {
    ...raw,
    requestedProvider: raw.requestedProvider ?? raw.requested_provider ?? null,
    fallbackUsed: raw.fallbackUsed ?? raw.fallback_used ?? false,
    fallbackReasonCode: raw.fallbackReasonCode ?? raw.fallback_reason_code ?? null,
    fallbackReason: raw.fallbackReason ?? raw.fallback_reason ?? null,
    cacheHit: raw.cacheHit ?? raw.cache_hit ?? false,
    analysisDurationMs: raw.analysisDurationMs ?? raw.analysis_duration_ms ?? null,
    contextFingerprint: raw.contextFingerprint ?? raw.context_fingerprint ?? null,
  };
}

export function isOllamaFallback(analysis: FallbackMetadata): boolean {
  return analysis.fallbackUsed === true || analysis.fallback_used === true;
}

export function isCacheHit(analysis: FallbackMetadata): boolean {
  return analysis.cacheHit === true || analysis.cache_hit === true;
}

export function formatAnalysisDuration(durationMs?: number | null): string | null {
  if (durationMs == null || Number.isNaN(durationMs) || durationMs < 0) {
    return null;
  }
  if (durationMs < 1000) {
    return `${Math.round(durationMs)} ms`;
  }
  if (durationMs < 60_000) {
    return `${(durationMs / 1000).toFixed(1)} s`;
  }
  const minutes = Math.floor(durationMs / 60_000);
  const seconds = Math.round((durationMs % 60_000) / 1000);
  return `${minutes}m ${seconds}s`;
}

export function buildFallbackNoticeCopy(analysis: FallbackMetadata) {
  if (!isOllamaFallback(analysis)) {
    return null;
  }

  const reason = analysis.fallbackReason ?? analysis.fallback_reason ?? null;
  const code = analysis.fallbackReasonCode ?? analysis.fallback_reason_code ?? null;
  const requestedProvider = analysis.requestedProvider ?? analysis.requested_provider ?? 'ollama';
  const requestedModel = analysis.model ?? null;

  return {
    title: 'AI fallback used',
    introduction: 'The Ollama model could not be used for this analysis.',
    reason,
    engineNote: 'The diagnostic below was generated by the deterministic rules engine.',
    requestedProvider,
    requestedModel,
    code,
  };
}
