#!/usr/bin/env python3
"""DEPRECATED / DEMO-ONLY.

Do not start this process on BANK-FW-01 in the living lab.
NetFlow is now generated by fprobe (start-softflowd.sh) from eth1 packets.
This module remains for historical unit tests of the DENY-log v5 encoder.
Running it beside softflowd would duplicate PORT_SCAN evidence.
"""

from __future__ import annotations

import hashlib
import os
import re
import socket
import struct
import time
from collections import OrderedDict

LOG_PATH = os.environ.get("BANK_FW_LOG", "/var/log/bank-firewall.log")
STATE_DIR = os.environ.get("BANK_FW_STATE_DIR", "/var/lib/bank-fw")
SENT_LOG = os.environ.get("BANK_FW_NETFLOW_SENT_LOG", "/var/log/bank-netflow-sent.log")
SEEN_FILE = os.path.join(STATE_DIR, "netflow.seen")
OFFSET_FILE = os.path.join(STATE_DIR, "netflow.offset")
CACHE_FILE = os.path.join(STATE_DIR, "netflow.host")
RUNTIME_FILE = os.environ.get("SENTINEL_NETFLOW_RUNTIME_FILE", "/opt/runtime/sentinel-netflow-host")

COLLECTOR_PORT = int(os.environ.get("SENTINEL_NETFLOW_PORT", "2055"))
FLUSH_IDLE_SEC = float(os.environ.get("NETFLOW_FLUSH_IDLE_SEC", "2"))
BYTES_PER_SYN = int(os.environ.get("NETFLOW_BYTES_PER_DENY", "64"))

SCAN_SRC = os.environ.get("SCAN_SRC", "10.0.0.10")
SCAN_DST = os.environ.get("SCAN_DST", "10.10.10.20")
SCAN_PORTS = {int(p) for p in os.environ.get("SCAN_PORTS", "21,22,23,80,443,3306,5432").split(",") if p.strip()}

FIELD_RE = re.compile(r"\b(SRC|DST|SPT|DPT|PROTO)=(\S+)")
IPV4_RE = re.compile(r"^\d+\.\d+\.\d+\.\d+$")


def is_ipv4(value: str) -> bool:
    return bool(value and IPV4_RE.match(value.strip()))


def read_first_token(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as handle:
            for line in handle:
                token = line.strip().split()[0] if line.strip() else ""
                if token:
                    return token
    except OSError:
        return ""
    return ""


def resolve_collector() -> str:
    env_host = os.environ.get("SENTINEL_NETFLOW_HOST", "").strip()
    if is_ipv4(env_host):
        return env_host

    cached = read_first_token(CACHE_FILE)
    if is_ipv4(cached):
        return cached

    runtime = read_first_token(RUNTIME_FILE)
    if is_ipv4(runtime):
        write_cache(runtime)
        return runtime

    # Last resort: Compose publishes 2055/udp on the Docker host.
    # banklab-mgmt gateway is stable; the collector container IP is not.
    gateway = os.environ.get("SENTINEL_MGMT_GATEWAY", "172.30.30.1")
    return gateway


def write_cache(ip_address: str) -> None:
    os.makedirs(STATE_DIR, exist_ok=True)
    with open(CACHE_FILE, "w", encoding="utf-8") as handle:
        handle.write(ip_address + "\n")


def load_seen() -> set[str]:
    try:
        with open(SEEN_FILE, encoding="utf-8") as handle:
            return {line.strip() for line in handle if line.strip()}
    except OSError:
        return set()


def append_seen(digest: str) -> None:
    os.makedirs(STATE_DIR, exist_ok=True)
    with open(SEEN_FILE, "a", encoding="utf-8") as handle:
        handle.write(digest + "\n")


def line_digest(line: str) -> str:
    return hashlib.md5(line.encode("utf-8", errors="replace")).hexdigest()


def parse_deny(line: str) -> dict | None:
    if "BANK-FW-01" not in line or "DENY" not in line:
        return None
    fields = {key: value for key, value in FIELD_RE.findall(line)}
    src = fields.get("SRC")
    dst = fields.get("DST")
    dpt = fields.get("DPT")
    proto = (fields.get("PROTO") or "TCP").split(",")[0].upper()
    if not src or not dst or not dpt:
        return None
    try:
        dest_port = int(dpt)
        src_port = int(fields.get("SPT") or "0")
    except ValueError:
        return None
    if src != SCAN_SRC or dst != SCAN_DST or dest_port not in SCAN_PORTS or proto != "TCP":
        return None
    return {
        "src": src,
        "dst": dst,
        "spt": src_port,
        "dpt": dest_port,
        "proto": proto,
    }


def ip_to_int(ip_address: str) -> int:
    return struct.unpack("!I", socket.inet_aton(ip_address))[0]


def encode_v5_header_times(now_unix: float, now_monotonic: float, boot_monotonic: float) -> tuple[int, int, int]:
    """NetFlow v5 header clocks.

    unix_secs / unix_nsecs are wall-clock UTC from time.time().
    SysUptime is milliseconds of time.monotonic() since exporter start.
    nfdump reconstructs UTC as unix_secs - (SysUptime - First) / 1000.
    Never put time.time() into First/Last or time.monotonic() into unix_secs.
    """
    unix_seconds = int(now_unix)
    unix_nsecs = int((now_unix - unix_seconds) * 1_000_000_000)
    sys_uptime_ms = max(1, int((now_monotonic - boot_monotonic) * 1000) + 1000)
    return sys_uptime_ms, unix_seconds, unix_nsecs


def encode_v5_flow_ms(
    first_monotonic: float,
    last_monotonic: float,
    boot_monotonic: float,
    sys_uptime_ms: int,
) -> tuple[int, int]:
    """First / Last are SysUptime-relative milliseconds (monotonic), not unix time."""
    first_ms = max(0, int((first_monotonic - boot_monotonic) * 1000) + 1000)
    last_ms = max(first_ms + 1, int((last_monotonic - boot_monotonic) * 1000) + 1000)
    last_ms = min(last_ms, sys_uptime_ms)
    return first_ms, last_ms


def build_record(flow: dict, sys_uptime_ms: int, boot: float) -> bytes:
    first_ms, last_ms = encode_v5_flow_ms(flow["first"], flow["last"], boot, sys_uptime_ms)
    return struct.pack(
        "!IIIHHIIIIHHBBBBHHBBH",
        ip_to_int(flow["src"]),
        ip_to_int(flow["dst"]),
        0,
        1,
        2,
        flow["packets"],
        flow["bytes"],
        first_ms,
        last_ms,
        flow["spt"],
        flow["dpt"],
        0,
        0x02,
        6,
        0,
        0,
        0,
        24,
        24,
        0,
    )


def build_packet(flows: list[dict], sequence: int, boot: float) -> bytes:
    sys_uptime_ms, unix_seconds, unix_nsecs = encode_v5_header_times(
        time.time(), time.monotonic(), boot
    )
    header = struct.pack(
        "!HHIIIIBBH",
        5,
        len(flows),
        sys_uptime_ms,
        unix_seconds,
        unix_nsecs,
        sequence,
        0,
        0,
        0,
    )
    records = b"".join(build_record(flow, sys_uptime_ms, boot) for flow in flows)
    return header + records


def send_packet(payload: bytes, collector: str) -> None:
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        sock.sendto(payload, (collector, COLLECTOR_PORT))


# Intentionally not a NetFlow v5 header (version would be 5 in the first two bytes).
NFCAPD_SLOT_FLUSH = b"\x00"


def send_nfcapd_slot_flush(collector: str) -> bool:
    """Close the collector's current nfcapd slot after a real export.

    nfcapd 1.7.5 may keep the latest slot in memory until another UDP
    datagram arrives, so the flush makes the real batch visible to
    nfdump/Import Latest immediately.

    The payload is not a valid NetFlow v5 packet and must not create
    Sentinel scan evidence. Failures are warnings only.
    """
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.settimeout(1.0)
            sock.sendto(NFCAPD_SLOT_FLUSH, (collector, COLLECTOR_PORT))
        return True
    except OSError as exc:
        print(
            "warning: nfcapd flush datagram failed dest=%s:%s error=%s"
            % (collector, COLLECTOR_PORT, exc),
            flush=True,
        )
        return False


class Exporter:
    def __init__(self) -> None:
        self.boot = time.monotonic()
        self.sequence = 0
        self.seen = load_seen()
        self.pending: OrderedDict[tuple, dict] = OrderedDict()
        self.last_event = 0.0
        os.makedirs(STATE_DIR, exist_ok=True)
        for path in (LOG_PATH, SENT_LOG, OFFSET_FILE, SEEN_FILE):
            directory = os.path.dirname(path)
            if directory:
                os.makedirs(directory, exist_ok=True)
        if not os.path.exists(LOG_PATH):
            open(LOG_PATH, "a", encoding="utf-8").close()
        if not os.path.exists(OFFSET_FILE):
            with open(OFFSET_FILE, "w", encoding="utf-8") as handle:
                handle.write("0\n")

    def offset(self) -> int:
        try:
            return int(read_first_token(OFFSET_FILE) or "0")
        except ValueError:
            return 0

    def set_offset(self, value: int) -> None:
        with open(OFFSET_FILE, "w", encoding="utf-8") as handle:
            handle.write(str(value) + "\n")

    def add_flow(self, parsed: dict) -> None:
        key = (parsed["src"], parsed["dst"], parsed["dpt"], parsed["proto"])
        now = time.monotonic()
        existing = self.pending.get(key)
        if existing is None:
            self.pending[key] = {
                "src": parsed["src"],
                "dst": parsed["dst"],
                "spt": parsed["spt"],
                "dpt": parsed["dpt"],
                "proto": parsed["proto"],
                "packets": 1,
                "bytes": BYTES_PER_SYN,
                "first": now,
                "last": now,
            }
        else:
            existing["packets"] += 1
            existing["bytes"] += BYTES_PER_SYN
            existing["last"] = now
        self.last_event = now

    def should_flush(self) -> bool:
        if not self.pending:
            return False
        ports = {key[2] for key in self.pending}
        if ports >= SCAN_PORTS:
            return True
        return (time.monotonic() - self.last_event) >= FLUSH_IDLE_SEC

    def flush(self) -> None:
        if not self.pending:
            return
        flows = list(self.pending.values())
        collector = resolve_collector()
        payload = build_packet(flows, self.sequence, self.boot)
        send_packet(payload, collector)
        self.sequence += len(flows)
        ports = sorted(flow["dpt"] for flow in flows)
        with open(SENT_LOG, "a", encoding="utf-8") as handle:
            handle.write(
                "sent records=%s src=%s dst=%s proto=TCP ports=%s dest=%s:%s bytes=%s\n"
                % (
                    len(flows),
                    flows[0]["src"],
                    flows[0]["dst"],
                    ",".join(str(port) for port in ports),
                    collector,
                    COLLECTOR_PORT,
                    len(payload),
                )
            )
        print(
            "exported NetFlow v5 records=%s SRC=%s DST=%s ports=%s dest=%s:%s"
            % (len(flows), flows[0]["src"], flows[0]["dst"], ports, collector, COLLECTOR_PORT),
            flush=True,
        )
        if send_nfcapd_slot_flush(collector):
            with open(SENT_LOG, "a", encoding="utf-8") as handle:
                handle.write("flush datagram sent dest=%s:%s\n" % (collector, COLLECTOR_PORT))
            print(
                "flush datagram sent dest=%s:%s" % (collector, COLLECTOR_PORT),
                flush=True,
            )
        self.pending.clear()

    def consume_new_lines(self) -> None:
        processed = self.offset()
        try:
            with open(LOG_PATH, encoding="utf-8", errors="replace") as handle:
                lines = handle.readlines()
        except OSError:
            return
        if len(lines) < processed:
            processed = 0
        n = 0
        for line in lines:
            n += 1
            if n <= processed:
                continue
            raw = line.rstrip("\n")
            digest = line_digest(raw)
            if digest in self.seen:
                self.set_offset(n)
                continue
            parsed = parse_deny(raw)
            if parsed is not None:
                self.add_flow(parsed)
                self.seen.add(digest)
                append_seen(digest)
            self.set_offset(n)
            if self.should_flush():
                self.flush()

    def run(self) -> None:
        collector = resolve_collector()
        print(
            "bank-fw-01 netflow exporter started dest=%s:%s log=%s"
            % (collector, COLLECTOR_PORT, LOG_PATH),
            flush=True,
        )
        while True:
            self.consume_new_lines()
            if self.should_flush():
                self.flush()
            time.sleep(0.5)


def main() -> None:
    Exporter().run()


if __name__ == "__main__":
    main()
